### ISSUE TITLE
Pull request builder fails with error 128

### ISSUE THREAD

**Issue by gregoryfischer** [ashwanthkumar/gocd-build-github-pull-requests#144]
Not sure why https://github.com/ashwanthkumar/gocd-build-github-pull-requests/issues/118 was closed as this is still an issue with the current non-release version 1.3.5 and is causing an incredible amount of pain in blocking development workflows with false failures.

UI error output
```
Material ebroker-common-pr-test checkout failed: The plugin sent a response that could not be understood by Go. Plugin returned with code '500' and the following response: '"Exception (Process exited with an error: 128 (Exit value: 128)) Occurred: [git, clone, --branch\u003dmaster, git@Git.corp.adobe.com:Stormcloud/ebroker-common.git, /go/pipelines/ebroker-common-pr-test] - null"'
The plugin sent a response that could not be understood by Go. Plugin returned with code '500' and the following response: '"Exception (Process exited with an error: 128 (Exit value: 128)) Occurred: [git, clone, --branch\u003dmaster, git@Git.corp.adobe.com:Stormcloud/ebroker-common.git, /go/pipelines/ebroker-common-pr-test] - null"'
```
Agent Log:
```
jvm 1    | 2020-04-02 17:07:02,025 [stdout] - 2020-04-02 17:07:02,011  INFO [scheduler-1] p.g.p.i.a.g.g.GitHubPRBuildPlugin:72 [plugin-github.pr] - destination: /go/pipelines/my-repo-pr-test. commit: b64c50f00d41d323fa72a866e82cea9cccd22245
jvm 1    | 2020-04-02 17:07:03,217 [stdout] - 2020-04-02 17:07:03,209  WARN [scheduler-1] p.g.p.i.a.g.g.GitHubPRBuildPlugin:102 [plugin-github.pr] - checkout: 
jvm 1    | 2020-04-02 17:07:03,217 [stdout] - java.lang.RuntimeException: Exception (Process exited with an error: 128 (Exit value: 128)) Occurred: [git, clone, --branch=master, git@Git.corp.adobe.com:Stormcloud/ebroker-common.git, /go/pipelines/my-repo-pr-test] - null
jvm 1    | 2020-04-02 17:07:03,217 [stdout] - 	at com.tw.go.plugin.cmd.Console.runOrBomb(Console.java:33)
jvm 1    | 2020-04-02 17:07:03,217 [stdout] - 	at com.tw.go.plugin.git.GitCmdHelper.runAndGetOutput(GitCmdHelper.java:397)
jvm 1    | 2020-04-02 17:07:03,217 [stdout] - 	at com.tw.go.plugin.git.GitCmdHelper.cloneRepository(GitCmdHelper.java:55)
jvm 1    | 2020-04-02 17:07:03,217 [stdout] - 	at com.tw.go.plugin.GitHelper.cloneOrFetch(GitHelper.java:38)
jvm 1    | 2020-04-02 17:07:03,217 [stdout] - 	at in.ashwanthkumar.gocd.github.GitHubPRBuildPlugin.handleCheckout(GitHubPRBuildPlugin.java:375)
jvm 1    | 2020-04-02 17:07:03,217 [stdout] - 	at in.ashwanthkumar.gocd.github.GitHubPRBuildPlugin.handle(GitHubPRBuildPlugin.java:126)
jvm 1    | 2020-04-02 17:07:03,220 [stdout] - 	at com.thoughtworks.go.plugin.infra.DefaultPluginManager.lambda$submitTo$0(DefaultPluginManager.java:134)
jvm 1    | 2020-04-02 17:07:03,220 [stdout] - 	at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.executeActionOnTheService(FelixGoPluginOSGiFramework.java:208)
jvm 1    | 2020-04-02 17:07:03,221 [stdout] - 	at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.doOn(FelixGoPluginOSGiFramework.java:164)
jvm 1    | 2020-04-02 17:07:03,221 [stdout] - 	at com.thoughtworks.go.plugin.infra.DefaultPluginManager.submitTo(DefaultPluginManager.java:131)
jvm 1    | 2020-04-02 17:07:03,221 [stdout] - 	at com.thoughtworks.go.plugin.access.PluginRequestHelper.submitRequest(PluginRequestHelper.java:49)
jvm 1    | 2020-04-02 17:07:03,221 [stdout] - 	at com.thoughtworks.go.plugin.access.scm.SCMExtension.checkout(SCMExtension.java:137)
jvm 1    | 2020-04-02 17:07:03,221 [stdout] - 	at com.thoughtworks.go.domain.materials.scm.PluggableSCMMaterialAgent.prepare(PluggableSCMMaterialAgent.java:60)
jvm 1    | 2020-04-02 17:07:03,221 [stdout] - 	at com.thoughtworks.go.remote.work.BuildWork.prepareJob(BuildWork.java:165)
jvm 1    | 2020-04-02 17:07:03,221 [stdout] - 	at com.thoughtworks.go.remote.work.BuildWork.build(BuildWork.java:118)
jvm 1    | 2020-04-02 17:07:03,221 [stdout] - 	at com.thoughtworks.go.remote.work.BuildWork.doWork(BuildWork.java:79)
jvm 1    | 2020-04-02 17:07:03,221 [stdout] - 	at com.thoughtworks.go.agent.JobRunner.run(JobRunner.java:53)
jvm 1    | 2020-04-02 17:07:03,225 [stdout] - 	at com.thoughtworks.go.agent.AgentHTTPClientController.retrieveWork(AgentHTTPClientController.java:147)
jvm 1    | 2020-04-02 17:07:03,225 [stdout] - 	at com.thoughtworks.go.agent.AgentHTTPClientController.work(AgentHTTPClientController.java:119)
jvm 1    | 2020-04-02 17:07:03,225 [stdout] - 	at com.thoughtworks.go.agent.AgentController.loop(AgentController.java:85)
jvm 1    | 2020-04-02 17:07:03,225 [stdout] - 	at jdk.internal.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
jvm 1    | 2020-04-02 17:07:03,225 [stdout] - 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
jvm 1    | 2020-04-02 17:07:03,225 [stdout] - 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
jvm 1    | 2020-04-02 17:07:03,225 [stdout] - 	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65)
jvm 1    | 2020-04-02 17:07:03,225 [stdout] - 	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
jvm 1    | 2020-04-02 17:07:03,225 [stdout] - 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
jvm 1    | 2020-04-02 17:07:03,225 [stdout] - 	at java.base/java.util.concurrent.FutureTask.runAndReset(Unknown Source)
jvm 1    | 2020-04-02 17:07:03,225 [stdout] - 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
jvm 1    | 2020-04-02 17:07:03,225 [stdout] - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
jvm 1    | 2020-04-02 17:07:03,225 [stdout] - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
jvm 1    | 2020-04-02 17:07:03,225 [stdout] - 	at java.base/java.lang.Thread.run(Unknown Source)
jvm 1    | 2020-04-02 17:07:03,225 [stdout] - Caused by: org.apache.commons.exec.ExecuteException: Process exited with an error: 128 (Exit value: 128)
jvm 1    | 2020-04-02 17:07:03,225 [stdout] - 	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404)
jvm 1    | 2020-04-02 17:07:03,225 [stdout] - 	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:166)
jvm 1    | 2020-04-02 17:07:03,225 [stdout] - 	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:153)
jvm 1    | 2020-04-02 17:07:03,225 [stdout] - 	at com.tw.go.plugin.cmd.Console.runOrBomb(Console.java:25)
jvm 1    | 2020-04-02 17:07:03,225 [stdout] - 	... 30 common frames omitted
jvm 1    | 2020-04-02 17:07:03,290 [stdout] - 2020-04-02 17:07:03,261 ERROR [scheduler-1] DefaultGoPublisher:137 - The plugin sent a response that could not be understood by Go. Plugin returned with code '500' and the following response: '"Exception (Process exited with an error: 128 (Exit value: 128)) Occurred: [git, clone, --branch\u003dmaster, git@Git.corp.adobe.com:Stormcloud/ebroker-common.git, /go/pipelines/ebroker-common-pr-test] - null"'
jvm 1    | 2020-04-02 17:07:03,290 [stdout] - java.lang.RuntimeException: The plugin sent a response that could not be understood by Go. Plugin returned with code '500' and the following response: '"Exception (Process exited with an error: 128 (Exit value: 128)) Occurred: [git, clone, --branch\u003dmaster, git@Git.corp.adobe.com:Stormcloud/ebroker-common.git, /go/pipelines/ebroker-common-pr-test] - null"'
jvm 1    | 2020-04-02 17:07:03,291 [stdout] - 	at com.thoughtworks.go.plugin.access.PluginRequestHelper.submitRequest(PluginRequestHelper.java:58)
jvm 1    | 2020-04-02 17:07:03,291 [stdout] - 	at com.thoughtworks.go.plugin.access.scm.SCMExtension.checkout(SCMExtension.java:137)
jvm 1    | 2020-04-02 17:07:03,291 [stdout] - 	at com.thoughtworks.go.domain.materials.scm.PluggableSCMMaterialAgent.prepare(PluggableSCMMaterialAgent.java:60)
```

Environment:
Server: gocd/gocd-server:v19.12.0 (docker image)
Agent(s): gocd/gocd-agent-ubuntu-18.04:v19.12.0 (docker image)
Plugin: v1.3.5

**Comment by plainsane** [comment]
same problem here on gocg 20.3 and 1.3.5 pointed at github enterprise

**Comment by Meet116** [comment]
Hi
Same issue here. Is there is any "@" or some thing in your github password or username which requireds URL encoding?
