### ISSUE TITLE
Adding material without name leads to non-specific error

### ISSUE THREAD

**Issue by mrmanc** [ashwanthkumar/gocd-build-github-pull-requests#145]
When I try to add a `Github` type material to a pipeline, if I have not named the material then I get an error message saying:

> We're sorry, but something went wrong. If you are the application owner check the logs for more information.

I had to go and comb the application logs (see truncated stack trace below) to work out that name was a required field. Can this requirement be removed, or the error message making more explicit?

<details>

```
2020-04-08 13:08:33,118 WARN  [qtp450829040-3404105] GoFileConfigDataSource:322 - Merged config update operation failed using fallback LAST VALID 15 partials. Exception message was: Number of errors: 1+
1. Please provide name;; 

com.thoughtworks.go.config.exceptions.GoConfigInvalidMergeException: Number of errors: 1+
1. Please provide name;; 

        at com.thoughtworks.go.config.MagicalGoConfigXmlLoader.validateCruiseConfig(MagicalGoConfigXmlLoader.java:139)
        at com.thoughtworks.go.config.MagicalGoConfigXmlLoader.preprocessAndValidate(MagicalGoConfigXmlLoader.java:126)
        at com.thoughtworks.go.config.MagicalGoConfigXmlWriter.write(MagicalGoConfigXmlWriter.java:76)
        at com.thoughtworks.go.config.GoFileConfigDataSource.configAsXml(GoFileConfigDataSource.java:533)
        at com.thoughtworks.go.config.GoFileConfigDataSource.getUnmergedConfig(GoFileConfigDataSource.java:465)
        at com.thoughtworks.go.config.GoFileConfigDataSource.trySavingConfig(GoFileConfigDataSource.java:449)
        at com.thoughtworks.go.config.GoFileConfigDataSource.writeWithLock(GoFileConfigDataSource.java:318)
        at com.thoughtworks.go.config.CachedGoConfig.writeWithLock(CachedGoConfig.java:153)
        at com.thoughtworks.go.config.GoConfigDao.updateConfig(GoConfigDao.java:117)
        at com.thoughtworks.go.server.service.GoConfigService.updateConfig(GoConfigService.java:306)
        at com.thoughtworks.go.server.service.GoConfigService.updateConfigFromUI(GoConfigService.java:357)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(JavaMethod.java:425)
        at org.jruby.javasupport.JavaMethod.invokeDirect(JavaMethod.java:292)
        at org.jruby.java.invokers.InstanceMethodInvoker.call(InstanceMethodInvoker.java:28)
        at org.jruby.java.invokers.InstanceMethodInvoker.call(InstanceMethodInvoker.java:90)
        at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:80)
        at org.jruby.ir.instructions.CallBase.interpret(CallBase.java:522)
        at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:360)
        at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:72)
        at org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:103)
        at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:90)
        at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:301)
        at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:82)
        at org.jruby.runtime.callsite.CachingCallSite.callIter(CachingCallSite.java:89)
        at org.jruby.ir.instructions.CallBase.interpret(CallBase.java:519)
        at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:360)
        at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:72)
        at org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:103)
        at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:90)
        at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:301)
        at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:82)
        at org.jruby.runtime.callsite.CachingCallSite.callIter(CachingCallSite.java:89)
        at org.jruby.ir.instructions.CallBase.interpret(CallBase.java:519)
        at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:360)
        at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:72)
        at org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:103)
        at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:90)
        at org.jruby.RubyClass.finvoke(RubyClass.java:525)
        at org.jruby.RubyBasicObject.send(RubyBasicObject.java:1752)
        at org.jruby.RubyKernel.send(RubyKernel.java:2182)
        at org.jruby.RubyKernel$INVOKER$s$send.call(RubyKernel$INVOKER$s$send.gen)
        at org.jruby.internal.runtime.methods.AliasMethod.call(AliasMethod.java:105)
        at org.jruby.ir.runtime.IRRuntimeHelpers.unresolvedSuper(IRRuntimeHelpers.java:1119)
        at org.jruby.ir.runtime.IRRuntimeHelpers.unresolvedSuperSplatArgs(IRRuntimeHelpers.java:1101)
```

</details>

The same error crops up if you add a duplicate material—once again a better error message would be useful. I suspect that this issue belongs in the GoCD repository… apologies if this is the case—I’m happy to recreate it there if so.

**Comment by ashwanthkumar** [comment]
Name is generally optional for a material unless you've more than 1 material in the pipeline. This again is an issue with GoCD and not the plugin.

**Comment by mrmanc** [comment]
Thanks for your reply. So is there no way that the plugin can provide the user with a better message when the config change fails? I didn’t raise this one in the GoCD repo as I thought that the interface to add a plugin was owned by this project, but let me know if I’m wrong and I’ll raise an issue there.

**Comment by ashwanthkumar** [comment]
In the [plugin interface](https://github.com/ashwanthkumar/gocd-build-github-pull-requests/blob/master/src/main/resources/views/scm.template.html), we don't collect name of the material. Thats the responsibility of the GoCD Server actually.

**Comment by mrmanc** [comment]
Okay, if that means that the error message also can’t be displayed by the plugin then I’ll go ahead and raise this against GoCD. Thanks!
