### ISSUE TITLE
Stash checkout fails

### ISSUE THREAD

**Issue by kerrmarin** [ashwanthkumar/gocd-build-github-pull-requests#27]
Hey,

I've set up the pipeline to build pull requests from Stash. The agent picks up the job appropriately, but when it tries to get the material, the integration fails.

Current setup:
Server: CentOS
Agent: Mac OS X
Version: 15.1.0

I had to use the IP address to connect to Stash (see issue #26 ).

The new pipeline has 1 material of type Stash.

go-agent.log:

```
2015-05-14 13:24:15,472 [loopThread] INFO  thoughtworks.go.work.DefaultGoPublisher:95 - Agent [WSWES12682, 104.15.12.125, e13a40b5-22af-46ab-b28a-5839e5d9311d] is reporting status [Preparing] to Go Server for Build [App-Test/3/Preintegration/1/Cocoapods/518]
2015-05-14 13:24:16,170 [loopThread] ERROR thoughtworks.go.work.DefaultGoPublisher:137 - Interaction with plugin with id 'stash.pr' implementing 'scm' extension failed while requesting for 'checkout'. Reason: [Unsuccessful response from plugin. Plugin returned with code '500' and the following response: '"Exception Occurred: [git, reset, --hard, HEAD] - /Users/svcmobile/Library/Application Support/Go Agent/pipelines/App-Test/pr"']
java.lang.RuntimeException: Interaction with plugin with id 'stash.pr' implementing 'scm' extension failed while requesting for 'checkout'. Reason: [Unsuccessful response from plugin. Plugin returned with code '500' and the following response: '"Exception Occurred: [git, reset, --hard, HEAD] - /Users/svcmobile/Library/Application Support/Go Agent/pipelines/App-Test/pr"']
        at com.thoughtworks.go.plugin.access.PluginRequestHelper.submitRequest(PluginRequestHelper.java:39)
        at com.thoughtworks.go.plugin.access.scm.SCMExtension.checkout(SCMExtension.java:173)
        at com.thoughtworks.go.domain.materials.scm.PluggableSCMMaterialAgent.prepare(PluggableSCMMaterialAgent.java:51)
        at com.thoughtworks.go.remote.work.BuildWork.prepareJob(BuildWork.java:168)
        at com.thoughtworks.go.remote.work.BuildWork.build(BuildWork.java:136)
        at com.thoughtworks.go.remote.work.BuildWork.doWork(BuildWork.java:91)
        at com.thoughtworks.go.agent.JobRunner.run(JobRunner.java:53)
        at com.thoughtworks.go.agent.AgentController.retrieveWork(AgentController.java:186)
        at com.thoughtworks.go.agent.AgentController.loop(AgentController.java:132)
        at sun.reflect.GeneratedMethodAccessor7.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:273)
        at org.springframework.scheduling.support.MethodInvokingRunnable.run(MethodInvokingRunnable.java:65)
        at org.springframework.scheduling.timer.DelegatingTimerTask.run(DelegatingTimerTask.java:70)
        at java.util.TimerThread.mainLoop(Timer.java:555)
        at java.util.TimerThread.run(Timer.java:505)
Caused by: java.lang.RuntimeException: Unsuccessful response from plugin. Plugin returned with code '500' and the following response: '"Exception Occurred: [git, reset, --hard, HEAD] - /Users/svcmobile/Library/Application Support/Go Agent/pipelines/App-Test/pr"'
        at com.thoughtworks.go.plugin.access.PluginRequestHelper.submitRequest(PluginRequestHelper.java:37)
        ... 16 more
2015-05-14 13:24:16,171 [loopThread] INFO  thoughtworks.go.work.DefaultGoPublisher:107 - Agent [WSWES12682, 104.15.12.125, e13a40b5-22af-46ab-b28a-5839e5d9311d] is reporting build result [Failed] to Go Server for Build [App-Test/3/Preintegration/1/Cocoapods/518]
2015-05-14 13:24:16,221 [loopThread] INFO  thoughtworks.go.work.DefaultGoPublisher:90 - Stopping Transmission for Build [App-Test/3/Preintegration/1/Cocoapods/518]
```

More logs:
```
2015-05-14 14:02:20,706 [loopThread] ERROR thoughtworks.go.work.DefaultGoPublisher:137 - Interaction with plugin with id 'stash.pr' implementing 'scm' extension failed while requesting for 'checkout'. Reason: [Unsuccessful response from plugin. Plugin returned with code '500' and the following response: '"Exception Occurred: [git, clean, -dff] - /Users/svcmobile/Library/Application Support/Go Agent/pipelines/Basket-PR"']
java.lang.RuntimeException: Interaction with plugin with id 'stash.pr' implementing 'scm' extension failed while requesting for 'checkout'. Reason: [Unsuccessful response from plugin. Plugin returned with code '500' and the following response: '"Exception Occurred: [git, clean, -dff] - /Users/svcmobile/Library/Application Support/Go Agent/pipelines/Basket-PR"']
        at com.thoughtworks.go.plugin.access.PluginRequestHelper.submitRequest(PluginRequestHelper.java:39)
        at com.thoughtworks.go.plugin.access.scm.SCMExtension.checkout(SCMExtension.java:173)
        at com.thoughtworks.go.domain.materials.scm.PluggableSCMMaterialAgent.prepare(PluggableSCMMaterialAgent.java:51)
        at com.thoughtworks.go.remote.work.BuildWork.prepareJob(BuildWork.java:168)
        at com.thoughtworks.go.remote.work.BuildWork.build(BuildWork.java:136)
        at com.thoughtworks.go.remote.work.BuildWork.doWork(BuildWork.java:91)
        at com.thoughtworks.go.agent.JobRunner.run(JobRunner.java:53)
        at com.thoughtworks.go.agent.AgentController.retrieveWork(AgentController.java:186)
        at com.thoughtworks.go.agent.AgentController.loop(AgentController.java:132)
        at sun.reflect.GeneratedMethodAccessor7.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:273)
        at org.springframework.scheduling.support.MethodInvokingRunnable.run(MethodInvokingRunnable.java:65)
        at org.springframework.scheduling.timer.DelegatingTimerTask.run(DelegatingTimerTask.java:70)
        at java.util.TimerThread.mainLoop(Timer.java:555)
        at java.util.TimerThread.run(Timer.java:505)
Caused by: java.lang.RuntimeException: Unsuccessful response from plugin. Plugin returned with code '500' and the following response: '"Exception Occurred: [git, clean, -dff] - /Users/svcmobile/Library/Application Support/Go Agent/pipelines/Basket-PR"'
        at com.thoughtworks.go.plugin.access.PluginRequestHelper.submitRequest(PluginRequestHelper.java:37)
        ... 16 more
2015-05-14 14:02:20,706 [loopThread] INFO  thoughtworks.go.work.DefaultGoPublisher:107 - Agent [WSWES12682,104.15.12.125, e13a40b5-22af-46ab-b28a-5839e5d9311d] is reporting build result [Failed] to Go Server for Build [Basket-PR/5/Preintegration/1/Cocoapods/530]
2015-05-14 14:02:20,756 [loopThread] INFO  thoughtworks.go.work.DefaultGoPublisher:90 - Stopping Transmission for Build [Basket-PR/5/Preintegration/1/Cocoapods/530]
2015-05-14 14:04:00,512 [loopThread] INFO  thoughtworks.go.work.DefaultGoPublisher:95 - Agent [WSWES12682, 104.15.12.125, e13a40b5-22af-46ab-b28a-5839e5d9311d] is reporting status [Preparing] to Go Server for Build [Basket-PR/6/Preintegration/1/Cocoapods/531]
2015-05-14 14:04:00,538 [loopThread] ERROR thoughtworks.go.work.DefaultGoPublisher:137 - Interaction with plugin with id 'stash.pr' implementing 'scm' extension failed while requesting for 'checkout'. Reason: [Unsuccessful response from plugin. Plugin returned with code '500' and the following response: '"Exception Occurred: [git, clone, --branch\u003dmaster, http://104.15.12.125/scm/mobilepods/pod-basketapi.git, \"/Users/svcmobile/Library/Application Support/Go Agent/pipelines/Basket-PR\"] - null"']
java.lang.RuntimeException: Interaction with plugin with id 'stash.pr' implementing 'scm' extension failed while requesting for 'checkout'. Reason: [Unsuccessful response from plugin. Plugin returned with code '500' and the following response: '"Exception Occurred: [git, clone, --branch\u003dmaster, http://104.15.12.125/scm/mobilepods/pod-basketapi.git, \"/Users/svcmobile/Library/Application Support/Go Agent/pipelines/Basket-PR\"] - null"']
        at com.thoughtworks.go.plugin.access.PluginRequestHelper.submitRequest(PluginRequestHelper.java:39)
        at com.thoughtworks.go.plugin.access.scm.SCMExtension.checkout(SCMExtension.java:173)
        at com.thoughtworks.go.domain.materials.scm.PluggableSCMMaterialAgent.prepare(PluggableSCMMaterialAgent.java:51)
        at com.thoughtworks.go.remote.work.BuildWork.prepareJob(BuildWork.java:168)
        at com.thoughtworks.go.remote.work.BuildWork.build(BuildWork.java:136)
        at com.thoughtworks.go.remote.work.BuildWork.doWork(BuildWork.java:91)
        at com.thoughtworks.go.agent.JobRunner.run(JobRunner.java:53)
        at com.thoughtworks.go.agent.AgentController.retrieveWork(AgentController.java:186)
        at com.thoughtworks.go.agent.AgentController.loop(AgentController.java:132)
        at sun.reflect.GeneratedMethodAccessor7.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:273)
        at org.springframework.scheduling.support.MethodInvokingRunnable.run(MethodInvokingRunnable.java:65)
        at org.springframework.scheduling.timer.DelegatingTimerTask.run(DelegatingTimerTask.java:70)
        at java.util.TimerThread.mainLoop(Timer.java:555)
        at java.util.TimerThread.run(Timer.java:505)
Caused by: java.lang.RuntimeException: Unsuccessful response from plugin. Plugin returned with code '500' and the following response: '"Exception Occurred: [git, clone, --branch\u003dmaster, http://104.15.12.125/scm/mobilepods/pod-basketapi.git, \"/Users/svcmobile/Library/Application Support/Go Agent/pipelines/Basket-PR\"] - null"'
        at com.thoughtworks.go.plugin.access.PluginRequestHelper.submitRequest(PluginRequestHelper.java:37)
        ... 16 more
```

And finally, the console log:

```
14:04:00.512 [go] Job Started: 2015-05-14 14:04:00 BST

14:04:00.512 [go] Start to prepare Basket-PR/6/Preintegration/1/Cocoapods on WSWES12682 [/Users/svcmobile/Library/Application Support/Go Agent]
14:04:00.521 [go] Start to update materials.

14:04:00.538 Interaction with plugin with id 'stash.pr' implementing 'scm' extension failed while requesting for 'checkout'. Reason: [Unsuccessful response from plugin. Plugin returned with code '500' and the following response: '"Exception Occurred: [git, clone, --branch\u003dmaster, http://104.15.12.125/scm/mobilepods/pod-basketapi.git, \"/Users/svcmobile/Library/Application Support/Go Agent/pipelines/Basket-PR\"] - null"']
14:04:00.593 [go] Job completed Basket-PR/6/Preintegration/1/Cocoapods on WSWES12682 [/Users/svcmobile/Library/Application Support/Go Agent]
```

Any help is appreciated.

**Comment by srinivasupadhya** [comment]
Can you post output of `plugin-stash.pr.log` that is on the agent?

**Comment by kerrmarin** [comment]
I'm able to run the stash plugin using docker, but it always fails using a mac (and we need it to run on a mac to build ios apps). Hopefully this helps :)

I'll have a look and see if I can find the plugin-stash.pr.log for this, but I don't think it's around anymore.

**Comment by kerrmarin** [comment]
Here's what I have in the `plugin-stash.pr.log` -- it's not the same job as above, but the errors are the same (i think):

```
2015-05-15 17:01:23,242  WARN [loopThread] GitHubPRBuildPlugin:67 - checkout: 
java.lang.RuntimeException: Exception Occurred: [git, clean, -dff] - /Users/svcnapmobile/Library/Application Support/Go Agent 2/pipelines/Basket-PR
	at com.tw.go.plugin.cmd.Console.runOrBomb(Console.java:33)
	at com.tw.go.plugin.git.GitCmdHelper.cleanUnversionedFiles(GitCmdHelper.java:220)
	at com.tw.go.plugin.git.GitCmdHelper.cleanAllUnversionedFiles(GitCmdHelper.java:215)
	at com.tw.go.plugin.GitHelper.fetchAndReset(GitHelper.java:100)
	at com.tw.go.plugin.GitHelper.fetchAndResetToHead(GitHelper.java:95)
	at com.tw.go.plugin.GitHelper.cloneOrFetch(GitHelper.java:41)
	at in.ashwanthkumar.gocd.github.GitHubPRBuildPlugin.handleCheckout(GitHubPRBuildPlugin.java:251)
	at in.ashwanthkumar.gocd.github.GitHubPRBuildPlugin.handle(GitHubPRBuildPlugin.java:85)
	at com.thoughtworks.go.plugin.infra.DefaultPluginManager$1.execute(DefaultPluginManager.java:172)
	at com.thoughtworks.go.plugin.infra.DefaultPluginManager$1.execute(DefaultPluginManager.java:167)
	at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.executeActionOnTheService(FelixGoPluginOSGiFramework.java:315)
	at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.doOn(FelixGoPluginOSGiFramework.java:245)
	at com.thoughtworks.go.plugin.infra.DefaultPluginManager.submitTo(DefaultPluginManager.java:167)
	at com.thoughtworks.go.plugin.access.PluginRequestHelper.submitRequest(PluginRequestHelper.java:33)
	at com.thoughtworks.go.plugin.access.scm.SCMExtension.checkout(SCMExtension.java:173)
	at com.thoughtworks.go.domain.materials.scm.PluggableSCMMaterialAgent.prepare(PluggableSCMMaterialAgent.java:51)
	at com.thoughtworks.go.remote.work.BuildWork.prepareJob(BuildWork.java:168)
	at com.thoughtworks.go.remote.work.BuildWork.build(BuildWork.java:136)
	at com.thoughtworks.go.remote.work.BuildWork.doWork(BuildWork.java:91)
	at com.thoughtworks.go.agent.JobRunner.run(JobRunner.java:53)
	at com.thoughtworks.go.agent.AgentController.retrieveWork(AgentController.java:186)
	at com.thoughtworks.go.agent.AgentController.loop(AgentController.java:132)
	at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:273)
	at org.springframework.scheduling.support.MethodInvokingRunnable.run(MethodInvokingRunnable.java:65)
	at org.springframework.scheduling.timer.DelegatingTimerTask.run(DelegatingTimerTask.java:70)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
Caused by: org.apache.commons.exec.ExecuteException: Process exited with an error: 128 (Exit value: 128)
	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:166)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:153)
	at com.tw.go.plugin.cmd.Console.runOrBomb(Console.java:25)
	... 29 more
2015-05-18 09:35:32,623  WARN [loopThread] GitHubPRBuildPlugin:62 - destination: /Users/svcnapmobile/Library/Application Support/Go Agent 2/pipelines/Basket-PR. commit: 52fd766073aaa9d259917b1e0fd887d892c3d36a
2015-05-18 09:35:33,024  WARN [loopThread] GitHubPRBuildPlugin:67 - checkout: 
java.lang.RuntimeException: Exception Occurred: [git, clone, --branch=master, http://10.5.13.244/scm/mobilepods/pod-nap-basketapi.git, "/Users/svcnapmobile/Library/Application Support/Go Agent 2/pipelines/Basket-PR"] - null
	at com.tw.go.plugin.cmd.Console.runOrBomb(Console.java:33)
	at com.tw.go.plugin.git.GitCmdHelper.cloneRepository(GitCmdHelper.java:57)
	at com.tw.go.plugin.GitHelper.cloneOrFetch(GitHelper.java:38)
	at in.ashwanthkumar.gocd.github.GitHubPRBuildPlugin.handleCheckout(GitHubPRBuildPlugin.java:251)
	at in.ashwanthkumar.gocd.github.GitHubPRBuildPlugin.handle(GitHubPRBuildPlugin.java:85)
	at com.thoughtworks.go.plugin.infra.DefaultPluginManager$1.execute(DefaultPluginManager.java:172)
	at com.thoughtworks.go.plugin.infra.DefaultPluginManager$1.execute(DefaultPluginManager.java:167)
	at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.executeActionOnTheService(FelixGoPluginOSGiFramework.java:315)
	at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.doOn(FelixGoPluginOSGiFramework.java:245)
	at com.thoughtworks.go.plugin.infra.DefaultPluginManager.submitTo(DefaultPluginManager.java:167)
	at com.thoughtworks.go.plugin.access.PluginRequestHelper.submitRequest(PluginRequestHelper.java:33)
	at com.thoughtworks.go.plugin.access.scm.SCMExtension.checkout(SCMExtension.java:173)
	at com.thoughtworks.go.domain.materials.scm.PluggableSCMMaterialAgent.prepare(PluggableSCMMaterialAgent.java:51)
	at com.thoughtworks.go.remote.work.BuildWork.prepareJob(BuildWork.java:168)
	at com.thoughtworks.go.remote.work.BuildWork.build(BuildWork.java:136)
	at com.thoughtworks.go.remote.work.BuildWork.doWork(BuildWork.java:91)
	at com.thoughtworks.go.agent.JobRunner.run(JobRunner.java:53)
	at com.thoughtworks.go.agent.AgentController.retrieveWork(AgentController.java:186)
	at com.thoughtworks.go.agent.AgentController.loop(AgentController.java:132)
	at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:273)
	at org.springframework.scheduling.support.MethodInvokingRunnable.run(MethodInvokingRunnable.java:65)
	at org.springframework.scheduling.timer.DelegatingTimerTask.run(DelegatingTimerTask.java:70)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
Caused by: org.apache.commons.exec.ExecuteException: Process exited with an error: 128 (Exit value: 128)
	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:166)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:153)
	at com.tw.go.plugin.cmd.Console.runOrBomb(Console.java:25)
	... 26 more
2015-05-18 10:02:53,203  WARN [loopThread] GitHubPRBuildPlugin:62 - destination: /Users/svcnapmobile/Library/Application Support/Go Agent 2/pipelines/Basket-PR. commit: 52fd766073aaa9d259917b1e0fd887d892c3d36a
2015-05-18 10:02:53,222  WARN [loopThread] GitHubPRBuildPlugin:67 - checkout: 
java.lang.RuntimeException: Exception Occurred: [git, clone, --branch=master, http://10.5.13.244/scm/mobilepods/pod-nap-basketapi.git, "/Users/svcnapmobile/Library/Application Support/Go Agent 2/pipelines/Basket-PR"] - null
	at com.tw.go.plugin.cmd.Console.runOrBomb(Console.java:33)
	at com.tw.go.plugin.git.GitCmdHelper.cloneRepository(GitCmdHelper.java:57)
	at com.tw.go.plugin.GitHelper.cloneOrFetch(GitHelper.java:38)
	at in.ashwanthkumar.gocd.github.GitHubPRBuildPlugin.handleCheckout(GitHubPRBuildPlugin.java:251)
	at in.ashwanthkumar.gocd.github.GitHubPRBuildPlugin.handle(GitHubPRBuildPlugin.java:85)
	at com.thoughtworks.go.plugin.infra.DefaultPluginManager$1.execute(DefaultPluginManager.java:172)
	at com.thoughtworks.go.plugin.infra.DefaultPluginManager$1.execute(DefaultPluginManager.java:167)
	at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.executeActionOnTheService(FelixGoPluginOSGiFramework.java:315)
	at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.doOn(FelixGoPluginOSGiFramework.java:245)
	at com.thoughtworks.go.plugin.infra.DefaultPluginManager.submitTo(DefaultPluginManager.java:167)
	at com.thoughtworks.go.plugin.access.PluginRequestHelper.submitRequest(PluginRequestHelper.java:33)
	at com.thoughtworks.go.plugin.access.scm.SCMExtension.checkout(SCMExtension.java:173)
	at com.thoughtworks.go.domain.materials.scm.PluggableSCMMaterialAgent.prepare(PluggableSCMMaterialAgent.java:51)
	at com.thoughtworks.go.remote.work.BuildWork.prepareJob(BuildWork.java:168)
	at com.thoughtworks.go.remote.work.BuildWork.build(BuildWork.java:136)
	at com.thoughtworks.go.remote.work.BuildWork.doWork(BuildWork.java:91)
	at com.thoughtworks.go.agent.JobRunner.run(JobRunner.java:53)
	at com.thoughtworks.go.agent.AgentController.retrieveWork(AgentController.java:186)
	at com.thoughtworks.go.agent.AgentController.loop(AgentController.java:132)
	at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:273)
	at org.springframework.scheduling.support.MethodInvokingRunnable.run(MethodInvokingRunnable.java:65)
	at org.springframework.scheduling.timer.DelegatingTimerTask.run(DelegatingTimerTask.java:70)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
Caused by: org.apache.commons.exec.ExecuteException: Process exited with an error: 128 (Exit value: 128)
	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:166)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:153)
	at com.tw.go.plugin.cmd.Console.runOrBomb(Console.java:25)
	... 26 more
2015-05-18 10:18:11,874  WARN [loopThread] GitHubPRBuildPlugin:62 - destination: /Users/svcnapmobile/Library/Application Support/Go Agent 2/pipelines/NAP-App-PR/pr. commit: 3c2d07dc0e9a23417d4881cc685d0feeee770579
2015-05-18 10:19:44,345  WARN [loopThread] GitHubPRBuildPlugin:67 - checkout: 
java.lang.OutOfMemoryError: Java heap space
	at org.eclipse.jgit.internal.storage.pack.BinaryDelta.apply(BinaryDelta.java:163)
	at org.eclipse.jgit.internal.storage.pack.BinaryDelta.apply(BinaryDelta.java:118)
	at org.eclipse.jgit.transport.PackParser.resolveDeltas(PackParser.java:610)
	at org.eclipse.jgit.transport.PackParser.resolveDeltas(PackParser.java:587)
	at org.eclipse.jgit.transport.PackParser.resolveDeltas(PackParser.java:550)
	at org.eclipse.jgit.transport.PackParser.parse(PackParser.java:507)
	at org.eclipse.jgit.internal.storage.file.ObjectDirectoryPackParser.parse(ObjectDirectoryPackParser.java:194)
	at org.eclipse.jgit.transport.PackParser.parse(PackParser.java:448)
	at org.eclipse.jgit.transport.BasePackFetchConnection.receivePack(BasePackFetchConnection.java:762)
	at org.eclipse.jgit.transport.BasePackFetchConnection.doFetch(BasePackFetchConnection.java:363)
	at org.eclipse.jgit.transport.TransportHttp$SmartHttpFetchConnection.doFetch(TransportHttp.java:783)
	at org.eclipse.jgit.transport.BasePackFetchConnection.fetch(BasePackFetchConnection.java:301)
	at org.eclipse.jgit.transport.BasePackFetchConnection.fetch(BasePackFetchConnection.java:291)
	at org.eclipse.jgit.transport.FetchProcess.fetchObjects(FetchProcess.java:247)
	at org.eclipse.jgit.transport.FetchProcess.executeImp(FetchProcess.java:160)
	at org.eclipse.jgit.transport.FetchProcess.execute(FetchProcess.java:122)
	at org.eclipse.jgit.transport.Transport.fetch(Transport.java:1138)
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:130)
	at org.eclipse.jgit.api.CloneCommand.fetch(CloneCommand.java:187)
	at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:127)
	at com.tw.go.plugin.jgit.JGitHelper.cloneRepository(JGitHelper.java:65)
	at com.tw.go.plugin.GitHelper.cloneOrFetch(GitHelper.java:38)
	at in.ashwanthkumar.gocd.github.GitHubPRBuildPlugin.handleCheckout(GitHubPRBuildPlugin.java:251)
	at in.ashwanthkumar.gocd.github.GitHubPRBuildPlugin.handle(GitHubPRBuildPlugin.java:85)
	at com.thoughtworks.go.plugin.infra.DefaultPluginManager$1.execute(DefaultPluginManager.java:172)
	at com.thoughtworks.go.plugin.infra.DefaultPluginManager$1.execute(DefaultPluginManager.java:167)
	at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.executeActionOnTheService(FelixGoPluginOSGiFramework.java:315)
	at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.doOn(FelixGoPluginOSGiFramework.java:245)
	at com.thoughtworks.go.plugin.infra.DefaultPluginManager.submitTo(DefaultPluginManager.java:167)
	at com.thoughtworks.go.plugin.access.PluginRequestHelper.submitRequest(PluginRequestHelper.java:33)
	at com.thoughtworks.go.plugin.access.scm.SCMExtension.checkout(SCMExtension.java:173)
	at com.thoughtworks.go.domain.materials.scm.PluggableSCMMaterialAgent.prepare(PluggableSCMMaterialAgent.java:51)
2015-05-18 13:05:52,407  WARN [loopThread] GitHubPRBuildPlugin:62 - destination: /Users/svcnapmobile/Library/Application Support/Go Agent 2/pipelines/NAP-App-PR/pr. commit: 3c2d07dc0e9a23417d4881cc685d0feeee770579
2015-05-18 13:07:03,157  WARN [loopThread] GitHubPRBuildPlugin:67 - checkout: 
java.lang.RuntimeException: Exception Occurred: [git, reset, --hard, HEAD] - /Users/svcnapmobile/Library/Application Support/Go Agent 2/pipelines/NAP-App-PR/pr
	at com.tw.go.plugin.cmd.Console.runOrBomb(Console.java:33)
	at com.tw.go.plugin.git.GitCmdHelper.runOrBomb(GitCmdHelper.java:382)
	at com.tw.go.plugin.git.GitCmdHelper.resetHard(GitCmdHelper.java:204)
	at com.tw.go.plugin.GitHelper.fetchAndReset(GitHelper.java:106)
	at com.tw.go.plugin.GitHelper.fetchAndResetToHead(GitHelper.java:95)
	at com.tw.go.plugin.GitHelper.cloneOrFetch(GitHelper.java:41)
	at in.ashwanthkumar.gocd.github.GitHubPRBuildPlugin.handleCheckout(GitHubPRBuildPlugin.java:251)
	at in.ashwanthkumar.gocd.github.GitHubPRBuildPlugin.handle(GitHubPRBuildPlugin.java:85)
	at com.thoughtworks.go.plugin.infra.DefaultPluginManager$1.execute(DefaultPluginManager.java:172)
	at com.thoughtworks.go.plugin.infra.DefaultPluginManager$1.execute(DefaultPluginManager.java:167)
	at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.executeActionOnTheService(FelixGoPluginOSGiFramework.java:315)
	at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.doOn(FelixGoPluginOSGiFramework.java:245)
	at com.thoughtworks.go.plugin.infra.DefaultPluginManager.submitTo(DefaultPluginManager.java:167)
	at com.thoughtworks.go.plugin.access.PluginRequestHelper.submitRequest(PluginRequestHelper.java:33)
	at com.thoughtworks.go.plugin.access.scm.SCMExtension.checkout(SCMExtension.java:173)
	at com.thoughtworks.go.domain.materials.scm.PluggableSCMMaterialAgent.prepare(PluggableSCMMaterialAgent.java:51)
	at com.thoughtworks.go.remote.work.BuildWork.prepareJob(BuildWork.java:168)
	at com.thoughtworks.go.remote.work.BuildWork.build(BuildWork.java:136)
	at com.thoughtworks.go.remote.work.BuildWork.doWork(BuildWork.java:91)
	at com.thoughtworks.go.agent.JobRunner.run(JobRunner.java:53)
	at com.thoughtworks.go.agent.AgentController.retrieveWork(AgentController.java:186)
	at com.thoughtworks.go.agent.AgentController.loop(AgentController.java:132)
	at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:273)
	at org.springframework.scheduling.support.MethodInvokingRunnable.run(MethodInvokingRunnable.java:65)
	at org.springframework.scheduling.timer.DelegatingTimerTask.run(DelegatingTimerTask.java:70)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
Caused by: org.apache.commons.exec.ExecuteException: Process exited with an error: 128 (Exit value: 128)
	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:166)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:153)
	at com.tw.go.plugin.cmd.Console.runOrBomb(Console.java:25)
	... 29 more
```

**Comment by kerrmarin** [comment]
Was that enough for you to debug the situation? I'd really like to be able to build pull requests through Stash :)

**Comment by srinivasupadhya** [comment]
@kerrmarin - is this fixed with GA release?

**Comment by kerrmarin** [comment]
Hi @srinivasupadhya, no this is not fixed as of the latest release (and neither is #29).

thanks!

**Comment by kerrmarin** [comment]
Hi @srinivasupadhya, I think this issue can be closed. I haven't experienced this in quite a while. I think it was due to a very large repo. #57 would also help with this.

**Comment by dokaspar** [comment]
Hi @kerrmarin,

What does "very large repo" mean? Every few weeks I observe exactly this error, as well. Would you call my clone a large repo?
```
remote: Counting objects: 23015, done.
remote: Compressing objects: 100% (10290/10290), done.
remote: Total 23015 (delta 11954), reused 18951 (delta 9236)
Receiving objects: 100% (23015/23015), 122.43 MiB | 3.78 MiB/s, done.
Resolving deltas: 100% (11954/11954), done.
```
What made me suspicious is the `--branch\u003dmaster` in the log statement, which you also seem to encounter. If you try a `git clone --branch\u003dmaster <url>` it will fail... I wonder if the plugin actually executes git with that wrong encoding or if that's just the way it appears in the log.

Regards,
Dominik

**Comment by kerrmarin** [comment]
hey @dokaspar, it's been a long time since this but I remember it was a couple GB in size.
