### ISSUE TITLE
Stash checkout OutOfMemory

### ISSUE THREAD

**Issue by kerrmarin** [ashwanthkumar/gocd-build-github-pull-requests#29]
The app that I am trying to clone is relatively large (i.e. repo is about 1.6GB).
The log for `plugin-stash.pr.log`:

```
2015-05-15 16:34:53,867  WARN [loopThread] GitHubPRBuildPlugin:62 - destination: /Users/svcmobile/Library/Application Support/Go Agent 3/pipelines/App-PR/pr. commit: 3c2d07dc0e9a23417d4881cc685d0feeee770579
2015-05-15 16:36:33,308  WARN [loopThread] GitHubPRBuildPlugin:67 - checkout:
java.lang.OutOfMemoryError: Java heap space
        at org.eclipse.jgit.internal.storage.pack.BinaryDelta.apply(BinaryDelta.java:163)
        at org.eclipse.jgit.internal.storage.pack.BinaryDelta.apply(BinaryDelta.java:118)
        at org.eclipse.jgit.transport.PackParser.resolveDeltas(PackParser.java:610)
        at org.eclipse.jgit.transport.PackParser.resolveDeltas(PackParser.java:587)
        at org.eclipse.jgit.transport.PackParser.resolveDeltas(PackParser.java:550)
        at org.eclipse.jgit.transport.PackParser.parse(PackParser.java:507)
        at org.eclipse.jgit.internal.storage.file.ObjectDirectoryPackParser.parse(ObjectDirectoryPackParser.java:194)
        at org.eclipse.jgit.transport.PackParser.parse(PackParser.java:448)
        at org.eclipse.jgit.transport.BasePackFetchConnection.receivePack(BasePackFetchConnection.java:762)
        at org.eclipse.jgit.transport.BasePackFetchConnection.doFetch(BasePackFetchConnection.java:363)
        at org.eclipse.jgit.transport.TransportHttp$SmartHttpFetchConnection.doFetch(TransportHttp.java:783)
        at org.eclipse.jgit.transport.BasePackFetchConnection.fetch(BasePackFetchConnection.java:301)
        at org.eclipse.jgit.transport.BasePackFetchConnection.fetch(BasePackFetchConnection.java:291)
        at org.eclipse.jgit.transport.FetchProcess.fetchObjects(FetchProcess.java:247)
        at org.eclipse.jgit.transport.FetchProcess.executeImp(FetchProcess.java:160)
        at org.eclipse.jgit.transport.FetchProcess.execute(FetchProcess.java:122)
        at org.eclipse.jgit.transport.Transport.fetch(Transport.java:1138)
        at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:130)
        at org.eclipse.jgit.api.CloneCommand.fetch(CloneCommand.java:187)
        at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:127)
        at com.tw.go.plugin.jgit.JGitHelper.cloneRepository(JGitHelper.java:65)
        at com.tw.go.plugin.GitHelper.cloneOrFetch(GitHelper.java:38)
        at in.ashwanthkumar.gocd.github.GitHubPRBuildPlugin.handleCheckout(GitHubPRBuildPlugin.java:251)
        at in.ashwanthkumar.gocd.github.GitHubPRBuildPlugin.handle(GitHubPRBuildPlugin.java:85)
        at com.thoughtworks.go.plugin.infra.DefaultPluginManager$1.execute(DefaultPluginManager.java:172)
        at com.thoughtworks.go.plugin.infra.DefaultPluginManager$1.execute(DefaultPluginManager.java:167)
        at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.executeActionOnTheService(FelixGoPluginOSGiFramework.java:315)
        at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.doOn(FelixGoPluginOSGiFramework.java:245)
        at com.thoughtworks.go.plugin.infra.DefaultPluginManager.submitTo(DefaultPluginManager.java:167)
        at com.thoughtworks.go.plugin.access.PluginRequestHelper.submitRequest(PluginRequestHelper.java:33)
        at com.thoughtworks.go.plugin.access.scm.SCMExtension.checkout(SCMExtension.java:173)
        at com.thoughtworks.go.domain.materials.scm.PluggableSCMMaterialAgent.prepare(PluggableSCMMaterialAgent.java:51)

```

**Comment by srinivasupadhya** [comment]
the implementation falls back to jgit if git is not locally installed on the box.
* can you install git on the agent machine (should be in path so git commands could be run by agent). once thats done it will prefer git commandline over jgit and you should not see this problem
* if you intend to use jgit then you might have to bump up xmx for the agent.

**Comment by kerrmarin** [comment]
Hi there,

git is installed on the agent:
```
~|⇒ git --version
git version 2.3.2 (Apple Git-55)
```
And:
```
~|⇒ which git 
/usr/bin/git
```

**Comment by srinivasupadhya** [comment]
That is odd :( will dig deeper into this after GA release.

**Comment by kerrmarin** [comment]
This also happens when running the plugin via Docker (https://github.com/gocd/gocd-docker/blob/master/Dockerfile.gocd-dev - after updating the agent and server to 15.1.0 in the dockerfile). Here's the logs from there:

Agent:

```
root@589dac1ef8a7:/var/log/go-agent# git --version
git version 1.9.1
```

go-agent.log:

```
2015-05-18 23:21:21,044 [loopThread] INFO  thoughtworks.go.work.DefaultGoPublisher:95 - Agent [589dac1ef8a7, 172.17.0.1, abfebab1-8dd8-4487-8f23-3e6f49526bf5] is reporting status [Preparing] to Go Server for Build [test/2/defaultStage/1/defaultJob/2]
2015-05-18 23:24:59,778 [loopThread] ERROR thoughtworks.go.work.DefaultGoPublisher:137 - Interaction with plugin with id 'stash.pr' implementing 'scm' extension failed while requesting for 'checkout'. Reason: [Unsuccessful response from plugin. Plugin returned with code '500' and the following response: '"Java heap space"']
java.lang.RuntimeException: Interaction with plugin with id 'stash.pr' implementing 'scm' extension failed while requesting for 'checkout'. Reason: [Unsuccessful response from plugin. Plugin returned with code '500' and the following response: '"Java heap space"']
	at com.thoughtworks.go.plugin.access.PluginRequestHelper.submitRequest(PluginRequestHelper.java:39)
	at com.thoughtworks.go.plugin.access.scm.SCMExtension.checkout(SCMExtension.java:173)
	at com.thoughtworks.go.domain.materials.scm.PluggableSCMMaterialAgent.prepare(PluggableSCMMaterialAgent.java:51)
	at com.thoughtworks.go.remote.work.BuildWork.prepareJob(BuildWork.java:168)
	at com.thoughtworks.go.remote.work.BuildWork.build(BuildWork.java:136)
	at com.thoughtworks.go.remote.work.BuildWork.doWork(BuildWork.java:91)
	at com.thoughtworks.go.agent.JobRunner.run(JobRunner.java:53)
	at com.thoughtworks.go.agent.AgentController.retrieveWork(AgentController.java:186)
	at com.thoughtworks.go.agent.AgentController.loop(AgentController.java:132)
	at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:273)
	at org.springframework.scheduling.support.MethodInvokingRunnable.run(MethodInvokingRunnable.java:65)
	at org.springframework.scheduling.timer.DelegatingTimerTask.run(DelegatingTimerTask.java:70)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
Caused by: java.lang.RuntimeException: Unsuccessful response from plugin. Plugin returned with code '500' and the following response: '"Java heap space"'
	at com.thoughtworks.go.plugin.access.PluginRequestHelper.submitRequest(PluginRequestHelper.java:37)
	... 16 more
2015-05-18 23:24:59,779 [loopThread] INFO  thoughtworks.go.work.DefaultGoPublisher:107 - Agent [589dac1ef8a7, 172.17.0.1, abfebab1-8dd8-4487-8f23-3e6f49526bf5] is reporting build result [Failed] to Go Server for Build [test/2/defaultStage/1/defaultJob/2]
2015-05-18 23:25:00,199 [loopThread] INFO  thoughtworks.go.work.DefaultGoPublisher:90 - Stopping Transmission for Build [test/2/defaultStage/1/defaultJob/2]
2015-05-18 23:42:10,439 [loopThread] INFO  thoughtworks.go.work.DefaultGoPublisher:95 - Agent [589dac1ef8a7, 172.17.0.1, abfebab1-8dd8-4487-8f23-3e6f49526bf5] is reporting status [Preparing] to Go Server for Build [test/3/defaultStage/1/defaultJob/3]
2015-05-18 23:42:10,496 [loopThread] ERROR thoughtworks.go.work.DefaultGoPublisher:137 - Interaction with plugin with id 'stash.pr' implementing 'scm' extension failed while requesting for 'checkout'. Reason: [Unsuccessful response from plugin. Plugin returned with code '500' and the following response: '"Exception Occurred: [git, checkout, -f, master] - /var/lib/go-agent/pipelines/test/pr"']
java.lang.RuntimeException: Interaction with plugin with id 'stash.pr' implementing 'scm' extension failed while requesting for 'checkout'. Reason: [Unsuccessful response from plugin. Plugin returned with code '500' and the following response: '"Exception Occurred: [git, checkout, -f, master] - /var/lib/go-agent/pipelines/test/pr"']
	at com.thoughtworks.go.plugin.access.PluginRequestHelper.submitRequest(PluginRequestHelper.java:39)
	at com.thoughtworks.go.plugin.access.scm.SCMExtension.checkout(SCMExtension.java:173)
	at com.thoughtworks.go.domain.materials.scm.PluggableSCMMaterialAgent.prepare(PluggableSCMMaterialAgent.java:51)
	at com.thoughtworks.go.remote.work.BuildWork.prepareJob(BuildWork.java:168)
	at com.thoughtworks.go.remote.work.BuildWork.build(BuildWork.java:136)
	at com.thoughtworks.go.remote.work.BuildWork.doWork(BuildWork.java:91)
	at com.thoughtworks.go.agent.JobRunner.run(JobRunner.java:53)
	at com.thoughtworks.go.agent.AgentController.retrieveWork(AgentController.java:186)
	at com.thoughtworks.go.agent.AgentController.loop(AgentController.java:132)
	at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:273)
	at org.springframework.scheduling.support.MethodInvokingRunnable.run(MethodInvokingRunnable.java:65)
	at org.springframework.scheduling.timer.DelegatingTimerTask.run(DelegatingTimerTask.java:70)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
Caused by: java.lang.RuntimeException: Unsuccessful response from plugin. Plugin returned with code '500' and the following response: '"Exception Occurred: [git, checkout, -f, master] - /var/lib/go-agent/pipelines/test/pr"'
	at com.thoughtworks.go.plugin.access.PluginRequestHelper.submitRequest(PluginRequestHelper.java:37)
	... 16 more
 ```

plugin-stash.pr.log

```
root@589dac1ef8a7:/var/log/go-server# cat plugin-stash.pr.log 
2015-05-18 23:16:18,680  INFO [91@MessageListener for MaterialUpdateListener] GitHubPRBuildPlugin:52 - Flyweight: /var/lib/go-server/pipelines/flyweight/88056006-dc7b-4830-a16c-243336803505
2015-05-18 23:20:56,211  INFO [91@MessageListener for MaterialUpdateListener] GitHubPRBuildPlugin:52 - Triggered build for master with head at 73d82060881ffa88b2449ed05db5d95589e907f2
2015-05-18 23:41:49,349  INFO [85@MessageListener for MaterialUpdateListener] GitHubPRBuildPlugin:52 - new commits: 1
2015-05-18 23:52:19,339  INFO [92@MessageListener for MaterialUpdateListener] GitHubPRBuildPlugin:52 - new commits: 1
```

**Comment by kerrmarin** [comment]
Hey,

Have you had a chance to look into this?

**Comment by srinivasupadhya** [comment]
No, sorry about that. Did you try the GA release? does the problem persist?

**Comment by kerrmarin** [comment]
I've tried the latest release (1.1), still have the same issues unfortunately.

**Comment by kerrmarin** [comment]
Hi there, I've tested release 1.2 and this issue is still there

**Comment by kerrmarin** [comment]
This can be worked around by increasing the -Xmx on the agent inside the Info.plist for Go Agent.app from:

```
        <dict>
            <key>AGENT_STARTUP_ARGS</key>
            <string>-Xms128m -Xmx256m</string>
        </dict>
```

to
```
        <dict>
            <key>AGENT_STARTUP_ARGS</key>
            <string>-Xms128m -Xmx2048m</string>
        </dict>
```

I don't know if it's possible to pass this in as a parameter, but that would be better than this solution.

**Comment by ashwanthkumar** [comment]
@kerrmarin We now have a v1.2.1 which removes jGit and uses only git command line. Please give that a shot and let us know if that fixes your problem.

**Comment by ashwanthkumar** [comment]
Closing the ticket. Please re-open if the issue still persist even after moving to v1.2.1.
