### ISSUE TITLE
git submodules broken over SSH

### ISSUE THREAD

**Issue by stevendgonzales** [ashwanthkumar/gocd-build-github-pull-requests#31]
For a repo with submodules, I am getting the below error.  Any advice?
```
2015-05-16 06:11:44,640  WARN [84@MessageListener for MaterialUpdateListener] GitHubPRBuildPlugin:67 - get latest revisions since:
java.lang.RuntimeException: Exception Occurred: [git, config, --get-regexp, ^submodule\..+\.url] - /var/lib/go-server/pipelines/flyweight/3d83eae3-92a0-4b48-83b5-8a72e7d44e8d
	at com.tw.go.plugin.cmd.Console.runOrBomb(Console.java:33)
	at com.tw.go.plugin.git.GitCmdHelper.runAndGetOutput(GitCmdHelper.java:386)
	at com.tw.go.plugin.git.GitCmdHelper.submoduleUrls(GitCmdHelper.java:233)
	at com.tw.go.plugin.git.GitCmdHelper.cleanAllUnversionedFiles(GitCmdHelper.java:211)
	at com.tw.go.plugin.GitHelper.fetchAndReset(GitHelper.java:100)
	at com.tw.go.plugin.GitHelper.fetchAndResetToHead(GitHelper.java:95)
	at com.tw.go.plugin.GitHelper.cloneOrFetch(GitHelper.java:41)
	at in.ashwanthkumar.gocd.github.GitHubPRBuildPlugin.handleLatestRevisionSince(GitHubPRBuildPlugin.java:185)
	at in.ashwanthkumar.gocd.github.GitHubPRBuildPlugin.handle(GitHubPRBuildPlugin.java:83)
	at com.thoughtworks.go.plugin.infra.DefaultPluginManager$1.execute(DefaultPluginManager.java:172)
	at com.thoughtworks.go.plugin.infra.DefaultPluginManager$1.execute(DefaultPluginManager.java:167)
	at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.executeActionOnTheService(FelixGoPluginOSGiFramework.java:315)
	at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.doOn(FelixGoPluginOSGiFramework.java:245)
	at com.thoughtworks.go.plugin.infra.DefaultPluginManager.submitTo(DefaultPluginManager.java:167)
	at com.thoughtworks.go.plugin.access.PluginRequestHelper.submitRequest(PluginRequestHelper.java:33)
	at com.thoughtworks.go.plugin.access.scm.SCMExtension.latestModificationSince(SCMExtension.java:154)
	at com.thoughtworks.go.server.service.materials.PluggableSCMMaterialPoller.modificationsSince(PluggableSCMMaterialPoller.java:77)
	at com.thoughtworks.go.server.service.materials.PluggableSCMMaterialPoller.modificationsSince(PluggableSCMMaterialPoller.java:46)
	at com.thoughtworks.go.server.service.MaterialService.modificationsSince(MaterialService.java:110)
	at com.thoughtworks.go.server.materials.ScmMaterialUpdater.insertLatestOrNewModifications(ScmMaterialUpdater.java:52)
	at com.thoughtworks.go.server.materials.PluggableSCMMaterialUpdater.insertLatestOrNewModifications(PluggableSCMMaterialUpdater.java:61)
	at com.thoughtworks.go.server.materials.MaterialDatabaseUpdater.insertLatestOrNewModifications(MaterialDatabaseUpdater.java:155)
	at com.thoughtworks.go.server.materials.MaterialDatabaseUpdater.updateMaterialWithNewRevisions(MaterialDatabaseUpdater.java:147)
	at com.thoughtworks.go.server.materials.MaterialDatabaseUpdater$2.doInTransaction(MaterialDatabaseUpdater.java:110)
	at com.thoughtworks.go.server.transaction.TransactionCallback.doWithExceptionHandling(TransactionCallback.java:24)
	at com.thoughtworks.go.server.transaction.TransactionTemplate$3.doInTransaction(TransactionTemplate.java:53)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:130)
	at com.thoughtworks.go.server.transaction.TransactionTemplate.executeWithExceptionHandling(TransactionTemplate.java:49)
	at com.thoughtworks.go.server.materials.MaterialDatabaseUpdater.updateMaterial(MaterialDatabaseUpdater.java:107)
	at com.thoughtworks.go.server.materials.MaterialUpdateListener.onMessage(MaterialUpdateListener.java:48)
	at com.thoughtworks.go.server.materials.MaterialUpdateListener.onMessage(MaterialUpdateListener.java:29)
	at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.runImpl(JMSMessageListenerAdapter.java:65)
	at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.run(JMSMessageListenerAdapter.java:50)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:166)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:153)
	at com.tw.go.plugin.cmd.Console.runOrBomb(Console.java:25)
```

**Comment by stevendgonzales** [comment]
It appears this does not work because the command `git config --get-regexp ^submodule\\..+\\.url` does not work because `git submodule init` as been called.

**Comment by stevendgonzales** [comment]
@srinivasupadhya It looks like submodule checkouts may have been broken in commit https://github.com/ashwanthkumar/gocd-build-github-pull-requests/commit/895d9a22324bd1f9e6f642eebc61871311cada1f
as it was working prior at https://github.com/ashwanthkumar/gocd-build-github-pull-requests/commit/9a594cd6edaa37ff9bc9bb14d9ddb8050e99ee64

**Comment by stevendgonzales** [comment]
trying to track down root cause, as it appears to come from https://github.com/srinivasupadhya/git-cmd/blob/master/src/com/tw/go/plugin/GitHelper.java

**Comment by stevendgonzales** [comment]
First exception is related to `com.tw.go.plugin.GitHelper.fetchAndReset(GitHelper.java:100)` in the git-cmd repo.  I have opened an issue and suggested a possible fix that I can implement here: https://github.com/srinivasupadhya/git-cmd/issues/1

**Comment by srinivasupadhya** [comment]
fixed in [git-cmd](https://github.com/srinivasupadhya/git-cmd). Will make new release with update soon.
