### ISSUE TITLE
git submodules broken over https

### ISSUE THREAD

**Issue by stevendgonzales** [ashwanthkumar/gocd-build-github-pull-requests#32]
when attempting to build a repo with git submodules over https, the following exception is raised:

```
2015-05-17 15:09:48,725  WARN [89@MessageListener for MaterialUpdateListener] GitHubPRBuildPlugin:67 - get latest revision:
java.lang.RuntimeException: checkout all sub-modules failed
	at com.tw.go.plugin.jgit.JGitHelper.checkoutAllModifiedFilesInSubmodules(JGitHelper.java:412)
	at com.tw.go.plugin.GitHelper.fetchAndReset(GitHelper.java:108)
	at com.tw.go.plugin.GitHelper.fetchAndResetToHead(GitHelper.java:95)
	at com.tw.go.plugin.GitHelper.cloneOrFetch(GitHelper.java:41)
	at in.ashwanthkumar.gocd.github.GitHubPRBuildPlugin.handleGetLatestRevision(GitHubPRBuildPlugin.java:156)
	at in.ashwanthkumar.gocd.github.GitHubPRBuildPlugin.handle(GitHubPRBuildPlugin.java:81)
	at com.thoughtworks.go.plugin.infra.DefaultPluginManager$1.execute(DefaultPluginManager.java:172)
	at com.thoughtworks.go.plugin.infra.DefaultPluginManager$1.execute(DefaultPluginManager.java:167)
	at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.executeActionOnTheService(FelixGoPluginOSGiFramework.java:315)
	at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.doOn(FelixGoPluginOSGiFramework.java:245)
	at com.thoughtworks.go.plugin.infra.DefaultPluginManager.submitTo(DefaultPluginManager.java:167)
	at com.thoughtworks.go.plugin.access.PluginRequestHelper.submitRequest(PluginRequestHelper.java:33)
	at com.thoughtworks.go.plugin.access.scm.SCMExtension.getLatestRevision(SCMExtension.java:135)
	at com.thoughtworks.go.server.service.materials.PluggableSCMMaterialPoller.latestModification(PluggableSCMMaterialPoller.java:61)
	at com.thoughtworks.go.server.service.materials.PluggableSCMMaterialPoller.latestModification(PluggableSCMMaterialPoller.java:46)
	at com.thoughtworks.go.server.service.MaterialService.latestModification(MaterialService.java:106)
	at com.thoughtworks.go.server.materials.LegacyMaterialChecker.findLatestModification(LegacyMaterialChecker.java:49)
	at com.thoughtworks.go.server.materials.ScmMaterialUpdater.insertLatestOrNewModifications(ScmMaterialUpdater.java:52)
	at com.thoughtworks.go.server.materials.ScmMaterialUpdater.addNewMaterialWithModifications(ScmMaterialUpdater.java:72)
	at com.thoughtworks.go.server.materials.PluggableSCMMaterialUpdater.addNewMaterialWithModifications(PluggableSCMMaterialUpdater.java:66)
	at com.thoughtworks.go.server.materials.MaterialDatabaseUpdater.addNewMaterialWithModifications(MaterialDatabaseUpdater.java:178)
	at com.thoughtworks.go.server.materials.MaterialDatabaseUpdater.initializeMaterialWithLatestRevision(MaterialDatabaseUpdater.java:134)
	at com.thoughtworks.go.server.materials.MaterialDatabaseUpdater.access$000(MaterialDatabaseUpdater.java:47)
	at com.thoughtworks.go.server.materials.MaterialDatabaseUpdater$1.doInTransaction(MaterialDatabaseUpdater.java:95)
	at com.thoughtworks.go.server.transaction.TransactionCallback.doWithExceptionHandling(TransactionCallback.java:24)
	at com.thoughtworks.go.server.transaction.TransactionTemplate$3.doInTransaction(TransactionTemplate.java:53)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:130)
	at com.thoughtworks.go.server.transaction.TransactionTemplate.executeWithExceptionHandling(TransactionTemplate.java:49)
	at com.thoughtworks.go.server.materials.MaterialDatabaseUpdater.updateMaterial(MaterialDatabaseUpdater.java:92)
	at com.thoughtworks.go.server.materials.MaterialUpdateListener.onMessage(MaterialUpdateListener.java:48)
	at com.thoughtworks.go.server.materials.MaterialUpdateListener.onMessage(MaterialUpdateListener.java:29)
	at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.runImpl(JMSMessageListenerAdapter.java:65)
	at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.run(JMSMessageListenerAdapter.java:50)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: sub-module checkout failed
	at com.tw.go.plugin.jgit.JGitHelper.checkoutSubmodule(JGitHelper.java:427)
	at com.tw.go.plugin.jgit.JGitHelper.checkoutAllModifiedFilesInSubmodules(JGitHelper.java:409)
	... 33 more
Caused by: org.eclipse.jgit.api.errors.InvalidRefNameException: Branch name <null> is not allowed
	at org.eclipse.jgit.api.CheckoutCommand.processOptions(CheckoutCommand.java:493)
	at org.eclipse.jgit.api.CheckoutCommand.call(CheckoutCommand.java:202)
	at com.tw.go.plugin.jgit.JGitHelper.checkoutSubmodule(JGitHelper.java:425)
	... 34 more
```

**Comment by stevendgonzales** [comment]
This looks to be related to the jgit [checkoutSubmodule()](https://github.com/srinivasupadhya/git-cmd/blob/master/src/com/tw/go/plugin/jgit/JGitHelper.java#420-433)

**Comment by srinivasupadhya** [comment]
fixed in [git-cmd](https://github.com/srinivasupadhya/git-cmd). Will make new release with update soon.

**Comment by stevendgonzales** [comment]
Thank you! I Will test out the new release
