### ISSUE TITLE
Intermittent clone failures

### ISSUE THREAD

**Issue by kerrmarin** [ashwanthkumar/gocd-build-github-pull-requests#51]
Hi,

This plugin intermittently fails with the following error:

```
09:21:53.108 Interaction with plugin with id 'stash.pr' implementing 'scm' extension failed while requesting for 'checkout'. Reason: [Unsuccessful response from plugin. Plugin returned with code '500' and the following response: '"clone failed"']
```

The output from `plugin-stash.pr.log`:

```
2015-09-02 09:21:53,106  WARN [loopThread] GitHubPRBuildPlugin:67 - checkout: 
java.lang.RuntimeException: clone failed
	at com.tw.go.plugin.jgit.JGitHelper.cloneRepository(JGitHelper.java:67)
	at com.tw.go.plugin.GitHelper.cloneOrFetch(GitHelper.java:38)
	at in.ashwanthkumar.gocd.github.GitHubPRBuildPlugin.handleCheckout(GitHubPRBuildPlugin.java:256)
	at in.ashwanthkumar.gocd.github.GitHubPRBuildPlugin.handle(GitHubPRBuildPlugin.java:90)
	at com.thoughtworks.go.plugin.infra.DefaultPluginManager$1.execute(DefaultPluginManager.java:172)
	at com.thoughtworks.go.plugin.infra.DefaultPluginManager$1.execute(DefaultPluginManager.java:167)
	at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.executeActionOnTheService(FelixGoPluginOSGiFramework.java:315)
	at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.doOn(FelixGoPluginOSGiFramework.java:245)
	at com.thoughtworks.go.plugin.infra.DefaultPluginManager.submitTo(DefaultPluginManager.java:167)
	at com.thoughtworks.go.plugin.access.PluginRequestHelper.submitRequest(PluginRequestHelper.java:32)
	at com.thoughtworks.go.plugin.access.scm.SCMExtension.checkout(SCMExtension.java:175)
	at com.thoughtworks.go.domain.materials.scm.PluggableSCMMaterialAgent.prepare(PluggableSCMMaterialAgent.java:51)
	at com.thoughtworks.go.remote.work.BuildWork.prepareJob(BuildWork.java:168)
	at com.thoughtworks.go.remote.work.BuildWork.build(BuildWork.java:136)
	at com.thoughtworks.go.remote.work.BuildWork.doWork(BuildWork.java:91)
	at com.thoughtworks.go.agent.JobRunner.run(JobRunner.java:53)
	at com.thoughtworks.go.agent.AgentController.retrieveWork(AgentController.java:186)
	at com.thoughtworks.go.agent.AgentController.loop(AgentController.java:132)
	at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:273)
	at org.springframework.scheduling.support.MethodInvokingRunnable.run(MethodInvokingRunnable.java:65)
	at org.springframework.scheduling.timer.DelegatingTimerTask.run(DelegatingTimerTask.java:70)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
Caused by: org.eclipse.jgit.api.errors.TransportException: Short read of block.
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:139)
	at org.eclipse.jgit.api.CloneCommand.fetch(CloneCommand.java:193)
	at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:133)
	at com.tw.go.plugin.jgit.JGitHelper.cloneRepository(JGitHelper.java:65)
	... 25 more
Caused by: org.eclipse.jgit.errors.TransportException: Short read of block.
	at org.eclipse.jgit.transport.BasePackFetchConnection.doFetch(BasePackFetchConnection.java:370)
	at org.eclipse.jgit.transport.TransportHttp$SmartHttpFetchConnection.doFetch(TransportHttp.java:779)
	at org.eclipse.jgit.transport.BasePackFetchConnection.fetch(BasePackFetchConnection.java:301)
	at org.eclipse.jgit.transport.BasePackFetchConnection.fetch(BasePackFetchConnection.java:291)
	at org.eclipse.jgit.transport.FetchProcess.fetchObjects(FetchProcess.java:245)
	at org.eclipse.jgit.transport.FetchProcess.executeImp(FetchProcess.java:161)
	at org.eclipse.jgit.transport.FetchProcess.execute(FetchProcess.java:122)
	at org.eclipse.jgit.transport.Transport.fetch(Transport.java:1138)
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:130)
	... 28 more
Caused by: java.io.EOFException: Short read of block.
	at org.eclipse.jgit.util.IO.readFully(IO.java:248)
	at org.eclipse.jgit.transport.PacketLineIn.readLength(PacketLineIn.java:186)
	at org.eclipse.jgit.transport.SideBandInputStream.needDataPacket(SideBandInputStream.java:158)
	at org.eclipse.jgit.transport.SideBandInputStream.read(SideBandInputStream.java:140)
	at org.eclipse.jgit.transport.PackParser.fill(PackParser.java:1131)
	at org.eclipse.jgit.transport.PackParser.access$000(PackParser.java:97)
	at org.eclipse.jgit.transport.PackParser$InflaterStream.read(PackParser.java:1664)
	at java.io.InputStream.read(InputStream.java:101)
	at org.eclipse.jgit.transport.PackParser.whole(PackParser.java:983)
	at org.eclipse.jgit.transport.PackParser.indexOneObject(PackParser.java:916)
	at org.eclipse.jgit.transport.PackParser.parse(PackParser.java:487)
	at org.eclipse.jgit.internal.storage.file.ObjectDirectoryPackParser.parse(ObjectDirectoryPackParser.java:194)
	at org.eclipse.jgit.transport.PackParser.parse(PackParser.java:448)
	at org.eclipse.jgit.transport.BasePackFetchConnection.receivePack(BasePackFetchConnection.java:762)
	at org.eclipse.jgit.transport.BasePackFetchConnection.doFetch(BasePackFetchConnection.java:363)
	... 36 more
```

The agent is running on a Mac Mini.

**Comment by albertpastrana** [comment]
I believe that's the same issue as #49

**Comment by ashwanthkumar** [comment]
@kerrmarin Do you have `git` utility on the PATH of the Go Agent? Personally I prefer `git` over `jgit`. The plugin checks for `git` on the PATH if not found falls back to `jgit` based implementation.

**Comment by ashwanthkumar** [comment]
@kerrmarin Please do try v1.2.1 release and let us know if that works for you. 

I'm closing this issue. Feel free to re-open if you're still facing issues.
