### ISSUE TITLE
Trouble when the pipeline is triggered by changes

### ISSUE THREAD

**Issue by agomezcafeto** [ashwanthkumar/gocd-build-github-pull-requests#81]
We are getting an exception when a change is made in a private repository, this is the trace:

```
2016-12-26 20:43:52,402  WARN [92@MessageListener for MaterialUpdateListener] GitHubPRBuildPlugin:67 - get latest revisions since: 
java.lang.RuntimeException: Exception Occurred: [git, checkout, -f, master] - /var/lib/go-server/pipelines/flyweight/c6678a30-645f-408e-8d76-e686437a21c3
	at com.tw.go.plugin.cmd.Console.runOrBomb(Console.java:33)
	at com.tw.go.plugin.git.GitCmdHelper.runAndGetOutput(GitCmdHelper.java:397)
	at com.tw.go.plugin.git.GitCmdHelper.runOrBomb(GitCmdHelper.java:385)
	at com.tw.go.plugin.git.GitCmdHelper.checkoutRemoteBranchToLocal(GitCmdHelper.java:61)
	at com.tw.go.plugin.GitHelper.fetchAndReset(GitHelper.java:108)
	at com.tw.go.plugin.GitHelper.fetchAndResetToHead(GitHelper.java:99)
	at com.tw.go.plugin.GitHelper.cloneOrFetch(GitHelper.java:41)
	at in.ashwanthkumar.gocd.github.GitHubPRBuildPlugin.handleLatestRevisionSince(GitHubPRBuildPlugin.java:244)
	at in.ashwanthkumar.gocd.github.GitHubPRBuildPlugin.handle(GitHubPRBuildPlugin.java:121)
	at com.thoughtworks.go.plugin.infra.DefaultPluginManager$1.execute(DefaultPluginManager.java:172)
	at com.thoughtworks.go.plugin.infra.DefaultPluginManager$1.execute(DefaultPluginManager.java:167)
	at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.executeActionOnTheService(FelixGoPluginOSGiFramework.java:315)
	at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.doOn(FelixGoPluginOSGiFramework.java:245)
	at com.thoughtworks.go.plugin.infra.DefaultPluginManager.submitTo(DefaultPluginManager.java:167)
	at com.thoughtworks.go.plugin.access.PluginRequestHelper.submitRequest(PluginRequestHelper.java:32)
	at com.thoughtworks.go.plugin.access.scm.SCMExtension.latestModificationSince(SCMExtension.java:156)
	at com.thoughtworks.go.server.service.materials.PluggableSCMMaterialPoller.modificationsSince(PluggableSCMMaterialPoller.java:77)
	at com.thoughtworks.go.server.service.materials.PluggableSCMMaterialPoller.modificationsSince(PluggableSCMMaterialPoller.java:46)
	at com.thoughtworks.go.server.service.MaterialService.modificationsSince(MaterialService.java:110)
	at com.thoughtworks.go.server.materials.ScmMaterialUpdater.insertLatestOrNewModifications(ScmMaterialUpdater.java:52)
	at com.thoughtworks.go.server.materials.PluggableSCMMaterialUpdater.insertLatestOrNewModifications(PluggableSCMMaterialUpdater.java:61)
	at com.thoughtworks.go.server.materials.MaterialDatabaseUpdater.insertLatestOrNewModifications(MaterialDatabaseUpdater.java:155)
	at com.thoughtworks.go.server.materials.MaterialDatabaseUpdater.updateMaterialWithNewRevisions(MaterialDatabaseUpdater.java:147)
	at com.thoughtworks.go.server.materials.MaterialDatabaseUpdater$2.doInTransaction(MaterialDatabaseUpdater.java:110)
	at com.thoughtworks.go.server.transaction.TransactionCallback.doWithExceptionHandling(TransactionCallback.java:24)
	at com.thoughtworks.go.server.transaction.TransactionTemplate$3.doInTransaction(TransactionTemplate.java:53)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:130)
	at com.thoughtworks.go.server.transaction.TransactionTemplate.executeWithExceptionHandling(TransactionTemplate.java:49)
	at com.thoughtworks.go.server.materials.MaterialDatabaseUpdater.updateMaterial(MaterialDatabaseUpdater.java:107)
	at com.thoughtworks.go.server.materials.MaterialUpdateListener.onMessage(MaterialUpdateListener.java:48)
	at com.thoughtworks.go.server.materials.MaterialUpdateListener.onMessage(MaterialUpdateListener.java:29)
	at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.runImpl(JMSMessageListenerAdapter.java:65)
	at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.run(JMSMessageListenerAdapter.java:50)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:166)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:153)
	at com.tw.go.plugin.cmd.Console.runOrBomb(Console.java:25)
	... 33 more
```

**Comment by ashwanthkumar** [comment]
From the stack trace it looks like the command 
```
git checkout -f master
```
failed with an exit code of 1. 

Can you please try running the above command in the location (`/var/lib/go-server/pipelines/flyweight/c6678a30-645f-408e-8d76-e686437a21c3 `) as the `go` user and check if that's working fine? 

Also is non-PR pipeline getting triggered and running fine for changes in this repo?

**Comment by ashwanthkumar** [comment]
@agomezcafeto Another reason for the failure would be if you don't have any `master` branch in your repo. Recently (as of [v1.3.0](https://github.com/ashwanthkumar/gocd-build-github-pull-requests/releases/tag/v1.3.0)) we've added support for specifying default branches for the SCM material instead of defaulting to master always. Please check if that helps too. 

I'm closing this issue for now, please feel free to re-open if you might have any more questions.
