### ISSUE TITLE
Ugly stack trace in the logs at plugin load

### ISSUE THREAD

**Issue by sgran** [ashwanthkumar/gocd-build-github-pull-requests#88]
I see this:
```
2017-02-01 19:51:01,262 ERROR [Thread-74] PluginSettingsMetadataLoader:84 - Failed to fetch Plugin Settings metadata for plugin : git.fb
java.lang.RuntimeException: Interaction with plugin with id 'git.fb' implementing 'scm' extension failed while requesting for 'go.plugin-settings.get-configuration'. Re
ason: [Unable to de-serialize json response. Empty response body]
        at com.thoughtworks.go.plugin.access.PluginRequestHelper.submitRequest(PluginRequestHelper.java:41)
        at com.thoughtworks.go.plugin.access.common.settings.AbstractExtension.getPluginSettingsConfiguration(AbstractExtension.java:50)
        at com.thoughtworks.go.plugin.access.common.settings.PluginSettingsMetadataLoader.fetchPluginSettingsMetaData(PluginSettingsMetadataLoader.java:74)
        at com.thoughtworks.go.plugin.access.common.settings.PluginSettingsMetadataLoader.pluginLoaded(PluginSettingsMetadataLoader.java:54)
        at com.thoughtworks.go.plugin.infra.DefaultPluginManager$FilterChangeListener.pluginLoaded(DefaultPluginManager.java:291)
        at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework$2.execute(FelixGoPluginOSGiFramework.java:353)
        at org.apache.commons.collections.CollectionUtils.forAllDo(CollectionUtils.java:389)
        at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.getBundle(FelixGoPluginOSGiFramework.java:111)
        at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.loadPlugin(FelixGoPluginOSGiFramework.java:97)
        at com.thoughtworks.go.plugin.infra.listeners.DefaultPluginJarChangeListener.refreshBundle(DefaultPluginJarChangeListener.java:152)
        at com.thoughtworks.go.plugin.infra.listeners.DefaultPluginJarChangeListener.addPlugin(DefaultPluginJarChangeListener.java:109)
        at com.thoughtworks.go.plugin.infra.listeners.DefaultPluginJarChangeListener.pluginJarAdded(DefaultPluginJarChangeListener.java:72)
        at com.thoughtworks.go.plugin.infra.monitor.DefaultPluginJarLocationMonitor$PluginLocationMonitorThread$DoOnAllListeners$1.execute(DefaultPluginJarLocationMonitor.java:303)
        at com.thoughtworks.go.plugin.infra.monitor.DefaultPluginJarLocationMonitor$PluginLocationMonitorThread$DoOnAllListeners.doOnAllPluginJarChangeListener(DefaultPluginJarLocationMonitor.java:334)
        at com.thoughtworks.go.plugin.infra.monitor.DefaultPluginJarLocationMonitor$PluginLocationMonitorThread$DoOnAllListeners.pluginJarAdded(DefaultPluginJarLocationMonitor.java:301)
        at com.thoughtworks.go.plugin.infra.monitor.DefaultPluginJarLocationMonitor$PluginLocationMonitorThread.notifyListenersOfAddedPlugins(DefaultPluginJarLocationMonitor.java:225)
        at com.thoughtworks.go.plugin.infra.monitor.DefaultPluginJarLocationMonitor$PluginLocationMonitorThread.loadAndNotifyPluginsFrom(DefaultPluginJarLocationMonitor.java:213)
        at com.thoughtworks.go.plugin.infra.monitor.DefaultPluginJarLocationMonitor$PluginLocationMonitorThread.oneShot(DefaultPluginJarLocationMonitor.java:206)
        at com.thoughtworks.go.plugin.infra.monitor.DefaultPluginJarLocationMonitor$PluginLocationMonitorThread.run(DefaultPluginJarLocationMonitor.java:194)
Caused by: java.lang.RuntimeException: Unable to de-serialize json response. Empty response body
        at com.thoughtworks.go.plugin.access.common.settings.PluginSettingsJsonMessageHandler1_0.responseMessageForPluginSettingsConfiguration(PluginSettingsJsonMessageHandler1_0.java:64)
        at com.thoughtworks.go.plugin.access.common.settings.AbstractExtension$1.onSuccess(AbstractExtension.java:53)
        at com.thoughtworks.go.plugin.access.common.settings.AbstractExtension$1.onSuccess(AbstractExtension.java:50)
        at com.thoughtworks.go.plugin.access.PluginRequestHelper.submitRequest(PluginRequestHelper.java:37)
        ... 18 more
```

It doesn't actually seem to do any harm, but it seems jarring.

Cheers,

**Comment by ashwanthkumar** [comment]
This error happens because the plugin doesn't have any plugin level settings to get from GoCD so from some version on 16.x they started throwing errors like this.
